allowBuilds:
  '@parcel/watcher': true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - baseline-browser-mapping@2.11.13
  - browserslist@4.28.8
